/**
 * Perpcast Mascots — the app's own 30-piece pixel-art ERC-721 collection on Robinhood Chain.
 * Art + metadata are generated by scripts/build-mascots.mjs and served from /nft/*. The contract
 * (contracts/PerpcastMascots.sol) is deployed once from the founder's wallet; its address is then
 * pinned via VITE_MASCOTS_CONTRACT so mint / OpenSea buttons light up for everyone.
 */
import { createPublicClient, encodeDeployData, encodeFunctionData, toHex, type Address, type Hex } from 'viem'
import artifact from './mascotsArtifact.json'
import { ROBINHOOD_CHAIN, type EIP1193Provider } from './wallet'
import { robinhoodTransport } from './rpc'

export const SITE = 'https://perpcast.app'
export const MASCOT_SUPPLY = 30
/** Deployed 2026-09-28 from the founder wallet on Robinhood Chain (chain 4663). */
export const MASCOTS_CONTRACT: Address | null = ((import.meta.env.VITE_MASCOTS_CONTRACT as string | undefined) || '0x4a77b8e0f5a9c86e0970ab53adfc5acecdcd23ab') as Address

export interface MascotTraits {
  Element: string
  Background: string
  Hat: string
  Item: string
  Aura: string
}
export interface MascotIndexItem {
  id: number
  name: string
  traits: MascotTraits
}
export interface MascotCollection {
  name: string
  symbol: string
  description: string
  supply: number
  items: MascotIndexItem[]
}

export const mascotImage = (id: number) => `/nft/img/${id}.png`

let indexCache: Promise<MascotCollection> | null = null
export function fetchMascotIndex(): Promise<MascotCollection> {
  if (!indexCache) {
    indexCache = fetch('/nft/collection.json')
      .then((r) => {
        if (!r.ok) throw new Error(`Could not load collection (${r.status})`)
        return r.json() as Promise<MascotCollection>
      })
      .catch((e: Error) => {
        indexCache = null
        throw e
      })
  }
  return indexCache
}

export function openSeaCollectionUrl(contract: Address | null) {
  return contract ? `https://opensea.io/assets/robinhood/${contract}` : 'https://opensea.io/'
}
export function openSeaAssetUrl(contract: Address, id: number) {
  return `https://opensea.io/assets/robinhood/${contract}/${id}`
}
export function explorerContractUrl(contract: Address) {
  return `${ROBINHOOD_CHAIN.explorer}/token/${contract}`
}

const ABI = artifact.abi
const BYTECODE = artifact.bytecode as Hex
const publicClient = createPublicClient({ transport: robinhoodTransport() })

export interface MascotsState {
  totalSupply: number
  mintOpen: boolean
  owner: Address
  minted: boolean
  ownedIds: number[]
}

export async function readMascotsState(contract: Address, account: Address | null): Promise<MascotsState> {
  const [totalSupply, mintOpen, owner, minted] = await Promise.all([
    publicClient.readContract({ address: contract, abi: ABI, functionName: 'totalSupply' }) as Promise<bigint>,
    publicClient.readContract({ address: contract, abi: ABI, functionName: 'mintOpen' }) as Promise<boolean>,
    publicClient.readContract({ address: contract, abi: ABI, functionName: 'owner' }) as Promise<Address>,
    account ? (publicClient.readContract({ address: contract, abi: ABI, functionName: 'minted', args: [account] }) as Promise<boolean>) : Promise.resolve(false),
  ])
  const n = Number(totalSupply)
  let ownedIds: number[] = []
  if (account && n > 0) {
    const owners = await Promise.all(
      Array.from({ length: n }, (_, i) => (publicClient.readContract({ address: contract, abi: ABI, functionName: 'ownerOf', args: [BigInt(i + 1)] }) as Promise<Address>).catch(() => null)),
    )
    ownedIds = owners.flatMap((o, i) => (o && o.toLowerCase() === account.toLowerCase() ? [i + 1] : []))
  }
  return { totalSupply: n, mintOpen, owner, minted, ownedIds }
}

function walletErrorMessage(e: unknown): string {
  const err = e as { code?: number; message?: string }
  if (err?.code === 4001) return 'Transaction rejected in wallet'
  if (err?.code === -32002) return 'A request is already pending — open your wallet to continue'
  return err?.message || 'Wallet could not send the transaction'
}

/** Deploy is kept under ~1.1M gas so it also fits wallets that cap unknown-chain txs at 1.2M. */
const DEPLOY_GAS_FLOOR = 1_190_000n
const CALL_GAS_FLOOR = 160_000n

function withTimeout<T>(p: Promise<T>, ms: number): Promise<T> {
  return new Promise((res, rej) => {
    const t = setTimeout(() => rej(new Error('timeout')), ms)
    p.then((v) => (clearTimeout(t), res(v)), (e) => (clearTimeout(t), rej(e)))
  })
}

async function send(provider: EIP1193Provider, tx: { from: Address; to?: Address; data: Hex }): Promise<Hex> {
  const floor = tx.to ? CALL_GAS_FLOOR : DEPLOY_GAS_FLOOR
  let gas = floor
  try {
    const est = await withTimeout(publicClient.estimateGas({ account: tx.from, to: tx.to, data: tx.data }), 4_000)
    gas = (est * 120n) / 100n
    if (gas < floor) gas = floor
  } catch (e) {
    if (tx.to && !(e instanceof Error && e.message === 'timeout')) throw new Error(walletErrorMessage(e))
  }
  let hash: Hex
  try {
    hash = (await provider.request({
      method: 'eth_sendTransaction',
      params: [{ from: tx.from, ...(tx.to ? { to: tx.to } : {}), data: tx.data, gas: toHex(gas) }],
    })) as Hex
  } catch (e) {
    throw new Error(walletErrorMessage(e))
  }
  const receipt = await publicClient.waitForTransactionReceipt({ hash, timeout: 180_000 })
  if (receipt.status !== 'success') {
    const sent = await publicClient.getTransaction({ hash }).catch(() => null)
    const why = sent && receipt.gasUsed >= sent.gas ? `Ran out of gas (wallet capped it at ${sent.gas.toLocaleString()}) — raise the gas limit in your wallet before confirming` : 'Transaction reverted'
    throw new Error(`${why} — ${ROBINHOOD_CHAIN.explorer}/tx/${hash}`)
  }
  return hash
}

/** Deploys the collection from the connected wallet; returns the new contract address. */
export async function deployMascots(provider: EIP1193Provider, from: Address): Promise<{ hash: Hex; address: Address }> {
  const data = encodeDeployData({ abi: ABI, bytecode: BYTECODE })
  const hash = await send(provider, { from, data })
  const receipt = await publicClient.getTransactionReceipt({ hash })
  if (!receipt.contractAddress) throw new Error('Deployment receipt has no contract address')
  return { hash, address: receipt.contractAddress }
}

export function mintMascot(provider: EIP1193Provider, from: Address, contract: Address): Promise<Hex> {
  return send(provider, { from, to: contract, data: encodeFunctionData({ abi: ABI, functionName: 'mint' }) })
}
