/**
 * Perpcast Mascots — the app's own 100-piece generative ERC-721 collection on Robinhood Chain.
 * Art + metadata are generated by scripts/gen-mascots.mjs and served from /nft/*. The contract
 * (contracts/PerpcastMascots.sol) is deployed once from the founder's wallet; its address is then
 * pinned via VITE_MASCOTS_CONTRACT so mint / OpenSea buttons light up for everyone.
 */
import { createPublicClient, encodeDeployData, encodeFunctionData, http, toHex, type Address, type Hex } from 'viem'
import artifact from './mascotsArtifact.json'
import { ROBINHOOD_CHAIN, type EIP1193Provider } from './wallet'

export const SITE = 'https://perpcast.app'
export const MASCOT_SUPPLY = 100
export const MASCOTS_CONTRACT: Address | null = ((import.meta.env.VITE_MASCOTS_CONTRACT as string | undefined) || null) as Address | null
export const MASCOTS_BASE_URI = `${SITE}/nft/meta/`
export const MASCOTS_CONTRACT_URI = `${SITE}/nft/collection.json`

export interface MascotTraits {
  Background: string
  Pattern: string
  Body: string
  Hat: string
  Eyes: string
  Item: string
  Mood: string
}
export interface MascotIndexItem {
  id: number
  name: string
  traits: MascotTraits
}
export interface MascotCollection {
  name: string
  symbol: string
  description: string
  supply: number
  items: MascotIndexItem[]
}

export const mascotImage = (id: number) => `/nft/img/${id}.svg`

let indexCache: Promise<MascotCollection> | null = null
export function fetchMascotIndex(): Promise<MascotCollection> {
  if (!indexCache) {
    indexCache = fetch('/nft/collection.json')
      .then((r) => {
        if (!r.ok) throw new Error(`Could not load collection (${r.status})`)
        return r.json() as Promise<MascotCollection>
      })
      .catch((e: Error) => {
        indexCache = null
        throw e
      })
  }
  return indexCache
}

export function openSeaCollectionUrl(contract: Address | null) {
  return contract ? `https://opensea.io/assets/robinhood/${contract}` : 'https://opensea.io/'
}
export function openSeaAssetUrl(contract: Address, id: number) {
  return `https://opensea.io/assets/robinhood/${contract}/${id}`
}
export function explorerContractUrl(contract: Address) {
  return `${ROBINHOOD_CHAIN.explorer}/token/${contract}`
}

const ABI = artifact.abi
const BYTECODE = artifact.bytecode as Hex
const publicClient = createPublicClient({ transport: http(ROBINHOOD_CHAIN.rpc, { batch: true }) })

export interface MascotsState {
  totalSupply: number
  mintOpen: boolean
  owner: Address
  minted: boolean
  ownedIds: number[]
}

export async function readMascotsState(contract: Address, account: Address | null): Promise<MascotsState> {
  const [totalSupply, mintOpen, owner, minted] = await Promise.all([
    publicClient.readContract({ address: contract, abi: ABI, functionName: 'totalSupply' }) as Promise<bigint>,
    publicClient.readContract({ address: contract, abi: ABI, functionName: 'mintOpen' }) as Promise<boolean>,
    publicClient.readContract({ address: contract, abi: ABI, functionName: 'owner' }) as Promise<Address>,
    account ? (publicClient.readContract({ address: contract, abi: ABI, functionName: 'minted', args: [account] }) as Promise<boolean>) : Promise.resolve(false),
  ])
  const n = Number(totalSupply)
  let ownedIds: number[] = []
  if (account && n > 0) {
    const owners = await Promise.all(
      Array.from({ length: n }, (_, i) => (publicClient.readContract({ address: contract, abi: ABI, functionName: 'ownerOf', args: [BigInt(i + 1)] }) as Promise<Address>).catch(() => null)),
    )
    ownedIds = owners.flatMap((o, i) => (o && o.toLowerCase() === account.toLowerCase() ? [i + 1] : []))
  }
  return { totalSupply: n, mintOpen, owner, minted, ownedIds }
}

function walletErrorMessage(e: unknown): string {
  const err = e as { code?: number; message?: string }
  if (err?.code === 4001) return 'Transaction rejected in wallet'
  if (err?.code === -32002) return 'A request is already pending — open your wallet to continue'
  return err?.message || 'Wallet could not send the transaction'
}

async function send(provider: EIP1193Provider, tx: { from: Address; to?: Address; data: Hex }): Promise<Hex> {
  const gas = await publicClient.estimateGas({ account: tx.from, to: tx.to, data: tx.data }).catch(() => undefined)
  let hash: Hex
  try {
    hash = (await provider.request({
      method: 'eth_sendTransaction',
      params: [{ from: tx.from, ...(tx.to ? { to: tx.to } : {}), data: tx.data, ...(gas ? { gas: toHex((gas * 125n) / 100n) } : {}) }],
    })) as Hex
  } catch (e) {
    throw new Error(walletErrorMessage(e))
  }
  const receipt = await publicClient.waitForTransactionReceipt({ hash, timeout: 180_000 })
  if (receipt.status !== 'success') throw new Error(`Transaction reverted — ${ROBINHOOD_CHAIN.explorer}/tx/${hash}`)
  return hash
}

/** Deploys the collection from the connected wallet; returns the new contract address. */
export async function deployMascots(provider: EIP1193Provider, from: Address): Promise<{ hash: Hex; address: Address }> {
  const data = encodeDeployData({ abi: ABI, bytecode: BYTECODE, args: [MASCOTS_BASE_URI, MASCOTS_CONTRACT_URI] })
  const hash = await send(provider, { from, data })
  const receipt = await publicClient.getTransactionReceipt({ hash })
  if (!receipt.contractAddress) throw new Error('Deployment receipt has no contract address')
  return { hash, address: receipt.contractAddress }
}

export function mintMascot(provider: EIP1193Provider, from: Address, contract: Address): Promise<Hex> {
  return send(provider, { from, to: contract, data: encodeFunctionData({ abi: ABI, functionName: 'mint' }) })
}

export function reserveMascots(provider: EIP1193Provider, from: Address, contract: Address, count: number): Promise<Hex> {
  return send(provider, { from, to: contract, data: encodeFunctionData({ abi: ABI, functionName: 'reserve', args: [from, BigInt(count)] }) })
}
